config/routes.rb
VincentTest::Application.routes.draw do
  
  match "s3_direct_upload" => "posts#s3_direct_upload", :via => :post, as: "s3_direct_upload"

  resources :posts
  root 'posts#index'
end

app/models/attachment.rb
# == Schema Information
#
# Table name: attachments
#
#  id                :integer          not null, primary key
#  attachable_id     :integer
#  attachable_type   :string(255)
#  file_file_name    :string(255)
#  file_content_type :string(255)
#  file_file_size    :integer
#  file_updated_at   :datetime
#  direct_upload_url :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#

class Attachment < ActiveRecord::Base

  belongs_to :attachable, :polymorphic => true

end

app/models/picture.rb
# == Schema Information
#
# Table name: pictures
#
#  id                 :integer          not null, primary key
#  imageable_id       :integer
#  imageable_type     :string(255)
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  created_at         :datetime
#  updated_at         :datetime
#

class Picture < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true

  has_attached_file :image, :styles => {
                            :small => "348X216" },
                            :default_url => "/assets/missing.png",
                            :storage => :s3,
                            :s3_host_name => "s3-#{ENV['S3_REGION']}.amazonaws.com",
                            :s3_region => ENV['S3_REGION'],
                            :s3_credentials => {:access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                                                :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY'],
                                                :bucket => ENV['S3_BUCKET_NAME'],
                                                }

  validates_attachment  :image,
        :presence => true,
        :content_type => { :content_type => ["image/jpeg", "image/gif", "image/png"] },
        :size => { :less_than => 5.megabyte }

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base

  has_many :attachments, as: :attachable
  has_many :pictures, as: :imageable

  accepts_nested_attributes_for :pictures, :allow_destroy => true
  accepts_nested_attributes_for :attachments, :allow_destroy => true

  def self.strong_parameters
    columns = [:id, :title, :content, :pictures_attributes => [:id, :image], :attachments_attributes => [:id, :direct_upload_url]]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order("created_at desc")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @post.pictures.build
    @post.attachments.build
  end

  def edit
    @post = Post.find(params[:id])
    if @post.pictures.count == 0
      @post.pictures.build
    end

    if @post.attachments.count == 0
      @post.attachments.build
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash["notice"] = "Post has been created."
      redirect_to posts_path 
    else
      flash["alert"] = "Post has not been created."
      render "new"       
    end
  end

  def update
    @post = Post.find(params[:id])
    if (@post.update_attributes(post_params))
      flash["notice"] = "Post has been updated."
      redirect_to posts_path 
    else
      flash["alert"] = "Post has not been updated."
      render "edit" 
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash["notice"] = "Post has been deleted."
    redirect_to posts_path 
  end

  def s3_direct_upload
    render json: {status: :ok}
  end

private
    def post_params
      columns = Post.strong_parameters
      params.require(:post)
      .permit(columns)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
    when "notice" then "alert alert-info"
    when "success" then "alert alert-success"
    when "error" then "alert alert-danger"
    when "alert" then "alert alert-danger"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_flash_messages.html.erb
<br/>
<% flash && flash.each do |name, msg| %>
  <div class="alert alert-dismissible <%= flash_class(name)%>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= msg.html_safe %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Vincent test</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active">
          <%= link_to "Post", posts_path %>
        </li>        
      </ul>      
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VincentTest</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render :partial => "layouts/header" %>
  <div class="container" style="padding-top: 40px;">
    <%= render "layouts/flash_messages" %>
    <%= yield %>
    <br/>
    <br/>
    <br/>
    <br/>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= s3_uploader_form callback_url: s3_direct_upload_url, class: 's3-direct-upload-form', id: "s3-uploader", callback_param: "attachment[direct_upload_url]", max_file_size: 1.megabytes do %>

  <%= file_field_tag :file, id: "s3_direct_upload_input" %>  

<% end %>

<%= form_for @post do |f| %>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control", placeholder: "Title" %>    
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control", placeholder: "Content" %>    
  </div>

  <hr>
  <h4>Picture</h4>
  <%= f.fields_for :pictures do |f2| %>  
    <label>
      <% if f2.object.image.present? %>
        <%= image_tag f2.object.image, id: "upload-image-preview" %>
      <% else %>
        <%= image_tag "", id: "upload-image-preview" %>
      <% end %>
      <%= f2.hidden_field :id %>  
      <br/>
      <div class="btn btn-success">Upload an image</div>
      <%= f2.file_field :image, id: "upload-image", style: "display: none;", accept: "image/*" %>  
    </label>
  <% end %> 

  <hr>
  <h4>Attachment <sup>(* max upload is 1mb)</sup></h4>
  <%= f.fields_for :attachments do |f2| %>  
    <%= f2.hidden_field :id %>  
    <%= f2.hidden_field :direct_upload_url, id: "attachment_direct_upload_url" %> 

    <a href="<%= f2.object.direct_upload_url %>" target="_blank" 
    style="<%= f2.object.direct_upload_url.present? ? "" : "display:none;" %>" id="attachment_direct_upload_link">
      <i class="fa fa-file file-icon"></i>
      <br/>
      download file
      <br/>
    </a>
    <br/>

    <label for="s3_direct_upload_input">
      <div class="btn btn-success">Upload a file</div>
    </label>
    <div class="upload js-progress-bars" style="display:none;">
      <div class="progress">
        <div class="bar" style="width: 0%"></div>
      </div>
    </div>


  <% end %>

  <br/>
  <br/>
  <div class="form-action">
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to "Cancel", posts_path %>    
  </div>
  
<% end %>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="pull-left">
      <h3>Edit post</h3>
    </div>
  </div>
</div>
<hr>
<%= render "form" %>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="pull-left">
      <h3>All posts</h3>
    </div>
    <div class="pull-right">
      <%= link_to "New post", new_post_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>
<hr>
<table class="table">
  <thead>
    <th class="col-sm-1">#</th>
    <th class="col-sm-8">Title</th>
    <th class="col-sm-3">Action</th>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.id %></td>
        <td><%= post.title %></td>
        <td>
          <%= link_to "Show", post_path(post), class: "btn btn-info" %> | 
          <%= link_to "Edit", edit_post_path(post), class: "btn btn-primary" %> | 
          <%= link_to "Delete", post_path(post), class: "btn btn-danger", data: {confirm: "Are you sure to delete this post?"}, method: :delete %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="pull-left">
      <h3>New post</h3>
    </div>
  </div>
</div>
<hr>
<%= render "form" %>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="pull-left">
      <h3><%= @post.title %></h3>
    </div>
  </div>
</div>
<hr>

<strong>Content:</strong>
<br/>
<%= @post.content %>
<br/>
<br/>

<strong>Picture:</strong><br/>
<% if @post.pictures.present? %>
  <%= image_tag @post.pictures.first.image(:small) %>
<% else %>
  <label class="label label-danger">There is no picture</label>
<% end %>
<br/>
<br/>


<strong>Attachment:</strong><br/>
<% if @post.attachments.present? %>
  <a href="<%= @post.attachments.first.direct_upload_url %>" target="_blank">
    <i class="fa fa-file file-icon"></i>
    <br/>
    download file
    <br/>
  </a>
<% else %>
  <label class="label label-danger">There is no image</label>
<% end %>

<br/>
<br/>